### ISSUE TITLE
Errors out if there're draft releases

### ISSUE THREAD

**Issue by Legend-Master** [andrewthetechie/gha-clone-releases#207]
```log
  File "gha_clone_releases/main.py", line 194, in <module>
  File "gha_clone_releases/main.py", line 148, in main
  File "gha_clone_releases/utils/releases.py", line 61, in get_missing_releases
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
[8] Failed to execute script 'main' due to unhandled exception!
```

**Comment by andrewthetechie** [comment]
Hello,

Thank you for filing an issue. To be able to look into this, can you link to a failed run of the workflow or provide a log of a failing workflow run with debug on?

**Comment by Legend-Master** [comment]
```log
2024-03-11T12:57:19.5649005Z ##[command]/usr/bin/docker run --name ghcrioandrewthetechieghaclonereleasesv190_abd9cc --label 97348e --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_DEST_TOKEN" -e "INPUT_SRC_REPO" -e "INPUT_DEST_REPO" -e "INPUT_COPY_ASSETS" -e "INPUT_SKIP_DRAFT" -e "INPUT_SRC_REPO_GITHUB_API_URL" -e "INPUT_DEST_REPO_GITHUB_API_URL" -e "INPUT_TARGET" -e "INPUT_SKIP_PRERELEASE" -e "INPUT_LIMIT" -e "INPUT_DRY_RUN" -e "INPUT_MIN_VERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_DEBUG" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/glash/glash":"/github/workspace" ghcr.io/andrewthetechie/gha-clone-releases:v1.9.0
2024-03-11T12:57:23.4908637Z Traceback (most recent call last):
2024-03-11T12:57:23.4936634Z ##[debug]AzurCircle/glash has 7 releases
2024-03-11T12:57:23.4937724Z   File "gha_clone_releases/main.py", line 194, in <module>
2024-03-11T12:57:23.4938585Z   File "gha_clone_releases/main.py", line 148, in main
2024-03-11T12:57:23.4939724Z   File "gha_clone_releases/utils/releases.py", line 61, in get_missing_releases
2024-03-11T12:57:23.4941238Z TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
2024-03-11T12:57:23.4942478Z [8] Failed to execute script 'main' due to unhandled exception!
2024-03-11T12:57:23.4944219Z ##[debug]AzurCircle/gagaga has 0 releases
2024-03-11T12:57:23.4945228Z ##[debug]Src: AzurCircle/glash
2024-03-11T12:57:23.4946225Z ##[debug]Dest: AzurCircle/gagaga
2024-03-11T12:57:23.4947106Z ##[debug]Target: None
2024-03-11T12:57:23.4948053Z ##[debug]Min Version: None
2024-03-11T12:57:23.4948879Z ##[debug]Skip Draft: True
2024-03-11T12:57:23.4950541Z ##[debug]Skip Prerelease: False
2024-03-11T12:57:23.4951444Z ##[debug]Copy Assets: True
2024-03-11T12:57:23.4952370Z ##[debug]Dry Run: False
2024-03-11T12:57:23.4953194Z ##[debug]Limit: 0
2024-03-11T12:57:23.4954410Z ##[debug]Source releases: <github.PaginatedList.PaginatedList object at 0x7f3852096ed0>
2024-03-11T12:57:23.4956077Z ##[debug]Dest releases: <github.PaginatedList.PaginatedList object at 0x7f38520953d0>
2024-03-11T12:57:23.4957707Z ##[debug]Source release: 0.2.0 is greater than None, will copy to destination
2024-03-11T12:57:23.4959171Z ##[debug]Source release: 0.1.5 is greater than None, will copy to destination
2024-03-11T12:57:23.4960733Z ##[debug]Source release: 0.1.4 is greater than None, will copy to destination
2024-03-11T12:57:23.4962545Z ##[debug]Source release: 0.1.3 is greater than None, will copy to destination
2024-03-11T12:57:23.4964135Z ##[debug]Source release: 0.1.2 is greater than None, will copy to destination
2024-03-11T12:57:23.4965801Z ##[debug]Source release: 0.1.1 is greater than None, will copy to destination
2024-03-11T12:57:23.4967345Z ##[debug]Source release: 0.1.0 is greater than None, will copy to destination
2024-03-11T12:57:23.6545218Z ##[debug]Docker Action run completed with exit code 1
2024-03-11T12:57:23.6678143Z ##[debug]Finishing: Run action
2024-03-11T12:57:23.6816806Z ##[debug]Starting: Complete job
2024-03-11T12:57:23.6819044Z Uploading runner diagnostic logs
2024-03-11T12:57:23.6866188Z ##[debug]Starting diagnostic file upload.
2024-03-11T12:57:23.6866881Z ##[debug]Setting up diagnostic log folders.
2024-03-11T12:57:23.6869821Z ##[debug]Creating diagnostic log files folder.
2024-03-11T12:57:23.6888029Z ##[debug]Copying 1 worker diagnostic logs.
2024-03-11T12:57:23.6903712Z ##[debug]Copying 1 runner diagnostic logs.
2024-03-11T12:57:23.6905199Z ##[debug]Zipping diagnostic files.
2024-03-11T12:57:23.6947457Z ##[debug]Uploading diagnostic metadata file.
2024-03-11T12:57:23.6971458Z ##[debug]Diagnostic file upload complete.
2024-03-11T12:57:23.6972386Z Completed runner diagnostic log upload
2024-03-11T12:57:23.6972843Z Cleaning up orphan processes
2024-03-11T12:57:23.7378512Z ##[debug]Finishing: Complete job
2024-03-11T12:57:23.7498034Z ##[debug]Finishing: mirror-release
```

**Comment by andrewthetechie** [comment]
This action is not under active development. If you want to PR a fix for this I can review and merge it.
